#  Create a new image from the base nodejs 7 image.
FROM node:9.11-alpine as builder

RUN apk update -f && \
   apk add bash

RUN apk add git
RUN apk add yarn

# Create the target directory in the image
RUN mkdir -p /usr/src/app/app

# Set the created directory as the working directory
WORKDIR /usr/src/app

# Copy the package.json inside the working directory
COPY package.json /usr/src/app

# Install required dependencies
RUN yarn install

# Copy the app application source files. You can use .dockerignore to exlcude files. Works just as .gitignore does.
COPY app /usr/src/app/app

RUN npm install -g forever 

EXPOSE 3000

# Healthcheck for when the Angular app is fully built
# HEALTHCHECK CMD curl --fail http://localhost || exit 1
# Start the application. This is the same as running ng serve.

CMD ["yarn", "run", "start-prod"]